# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://rahulguha.com/"  # Include trailing slash
title = "Rahul Guha"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright © 2024, Rahul Guha; all rights reserved."
# canonifyurls = true
# favicon = "icons/favicon-32x32.png"
theme = "PaperMod"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10
